### ISSUE TITLE
Please support dart 2.12.0.

### ISSUE THREAD

**Issue by xclud** [peiffer-innovations/yaon#12]
There are many projects that use dart SDK `2.12.0`. Sticking with the latest dart SDK (2.19 in this case) renders the package unusable for almost every project.

Please support dart 2.12.0.

**Comment by jpeiffer** [comment]
I plan to keep on the latest-stable SDK provided by Flutter for my packages.  You're welcome to fork this and lower the SDK requirements should that help.
